@extends('layouts.app')
@section('content')
<style>
.tag-page-card{background:#fff;border:1px solid #e2e8f0;border-radius:16px;box-shadow:0 6px 20px rgba(15,23,42,.05);overflow:hidden}.tag-head{padding:18px 22px;border-bottom:1px solid #e2e8f0}.tag-form .form-control{min-height:44px;border-radius:9px}.tag-color{width:48px;height:44px;padding:4px;border:1px solid #cbd5e1;border-radius:9px}.tag-pill{display:inline-flex;align-items:center;color:#fff;border-radius:999px;padding:6px 12px;font-size:12px;font-weight:700}.tag-action{width:34px;height:34px;border:0;border-radius:8px;display:inline-flex;align-items:center;justify-content:center}.tag-table td,.tag-table th{padding:14px 18px;vertical-align:middle}
</style>
<main class="py-3"><div class="container-fluid">
 <div class="mb-4"><h4 class="fw-bold mb-1"><i class="fas fa-tags text-primary me-2"></i>Tag Master</h4><p class="text-muted mb-0">Lead aur Deal ke liye reusable tags manage karein.</p></div>
 @if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif @if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif
 <div class="row g-4"><div class="col-lg-4"><div class="tag-page-card"><div class="tag-head"><h6 class="fw-bold mb-1">Create Tag</h6><small class="text-muted">Tag ka naam likhkar create karein.</small></div><form class="p-3 tag-form" method="POST" action="{{route('tags.store')}}">@csrf<div class="mb-4"><label class="form-label fw-semibold">Tag name</label><input class="form-control" name="name" value="{{old('name')}}" placeholder="e.g. VIP Client" required></div><button class="btn btn-primary w-100"><i class="fas fa-plus me-1"></i>Create Tag</button></form></div></div>
 <div class="col-lg-8"><div class="tag-page-card"><div class="tag-head"><h6 class="fw-bold mb-1">Available Tags</h6><small class="text-muted">Tags Lead aur Deal dono me use honge.</small></div><div class="table-responsive"><table class="table tag-table mb-0"><thead class="table-light"><tr><th>Tag</th><th>Lead usage</th><th>Deal usage</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($tags as $tag)<tr><td><span class="tag-pill" style="background:{{$tag->color}}">{{$tag->name}}</span></td><td>{{$tag->leads_count}}</td><td>{{$tag->orders_count}}</td><td class="text-end"><button class="tag-action bg-primary-subtle text-primary me-1" data-bs-toggle="modal" data-bs-target="#editTag{{$tag->id}}"><i class="fas fa-pen"></i></button><form class="d-inline" method="POST" action="{{route('tags.destroy',$tag)}}">@csrf @method('DELETE')<button class="tag-action bg-danger-subtle text-danger" onclick="return confirm('Delete this tag?')"><i class="fas fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-5">No tags created.</td></tr>@endforelse</tbody></table></div></div></div></div>
 @foreach($tags as $tag)<div class="modal fade" id="editTag{{$tag->id}}" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 rounded-4"><form method="POST" action="{{route('tags.update',$tag)}}">@csrf @method('PUT')<div class="modal-header"><h6 class="modal-title fw-bold">Edit Tag</h6><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label fw-semibold">Tag name</label><input class="form-control" name="name" value="{{$tag->name}}" required></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Update</button></div></form></div></div></div>@endforeach
</div></main>
@endsection
